const getApplications=()=>{try{const data=JSON.parse(localStorage.getItem('vslApplications')||'[]');return Array.isArray(data)?data:[]}catch(error){localStorage.removeItem('vslApplications');return[]}};
const saveApplications=applications=>localStorage.setItem('vslApplications',JSON.stringify(applications));
function seedDemoApplicant(){const applications=getApplications();if(applications.some(item=>item.email==='demo.seller@virtualspacelotto.com'))return;applications.push({id:'VSL-DEMO-0001',name:'Demo Seller',email:'demo.seller@virtualspacelotto.com',mobile:'09171234567',address:'Manila, Philippines',hasPermit:'yes',status:'APPROVED',followUp:false,password:'Seller123!'});saveApplications(applications)}
seedDemoApplicant();
document.getElementById('adminPassword').addEventListener('keydown',event=>{if(event.key==='Enter')loginAdmin()});
function useDemoAdmin(){document.getElementById('adminEmail').value='admin@virtualspacelotto.com';document.getElementById('adminPassword').value='admin123';loginAdmin()}function loginAdmin(){const email=document.getElementById('adminEmail').value.trim().toLowerCase(),password=document.getElementById('adminPassword').value.trim(),message=document.getElementById('loginMessage');if(email!=='admin@virtualspacelotto.com'||password!=='admin123'){message.textContent='Incorrect admin email or password. Use the Demo Admin Login button.';return}sessionStorage.setItem('vslAdminSession','active');showDashboard()}
function showDashboard(){document.getElementById('adminLoginView').hidden=true;document.getElementById('adminDashboard').hidden=false;renderAdmin()}
function logoutAdmin(){sessionStorage.removeItem('vslAdminSession');document.getElementById('adminDashboard').hidden=true;document.getElementById('adminLoginView').hidden=false}
function card(application,forInquiry=false){const item=document.createElement('article'),title=document.createElement('h3'),details=document.createElement('p'),status=document.createElement('p');title.textContent=application.name;details.textContent=application.email+' • '+application.mobile;status.textContent=forInquiry?'Needs follow-up':'Status: '+application.status;item.append(title,details,status);const actions=document.createElement('div');actions.className='actions';if(!forInquiry&&application.status!=='APPROVED'){const approve=document.createElement('button');approve.textContent='Approve';approve.onclick=()=>updateApplication(application.id,{status:'APPROVED'});actions.append(approve)}if(forInquiry){const done=document.createElement('button');done.className='secondary';done.textContent='Mark resolved';done.onclick=()=>updateApplication(application.id,{followUp:false});actions.append(done)}if(actions.children.length)item.append(actions);return item}
function renderAdmin(){const applications=getApplications(),filter=document.getElementById('applicationFilter').value,pending=applications.filter(item=>item.status!=='APPROVED'),approved=applications.filter(item=>item.status==='APPROVED'),followUps=applications.filter(item=>item.followUp);document.getElementById('pendingCount').textContent=pending.length;document.getElementById('approvedCount').textContent=approved.length;document.getElementById('followUpCount').textContent=followUps.length;const visible=filter==='pending'?pending:filter==='approved'?approved:applications;const applicationList=document.getElementById('applicationList'),inquiryList=document.getElementById('inquiryList');applicationList.replaceChildren();inquiryList.replaceChildren();if(!visible.length)applicationList.textContent='No applications in this view.';else visible.forEach(application=>applicationList.append(card(application)));if(!followUps.length)inquiryList.textContent='No open follow-ups.';else followUps.forEach(application=>inquiryList.append(card(application,true)))}
function updateApplication(id,changes){const applications=getApplications(),application=applications.find(item=>item.id===id);if(!application)return;Object.assign(application,changes);saveApplications(applications);renderAdmin()}
if(sessionStorage.getItem('vslAdminSession')==='active')showDashboard();
