const permitSelect=document.getElementById('hasPermit'),supportingDocLabel=document.getElementById('supportingDocLabel');
const getApplications=()=>JSON.parse(localStorage.getItem('vslApplications')||'[]');
const saveApplications=applications=>localStorage.setItem('vslApplications',JSON.stringify(applications));
function seedDemoApplicant(){const applications=getApplications();if(applications.some(item=>item.email==='demo.seller@virtualspacelotto.com'))return;applications.push({id:'VSL-DEMO-0001',name:'Demo Seller',email:'demo.seller@virtualspacelotto.com',mobile:'09171234567',address:'Manila, Philippines',hasPermit:'yes',status:'APPROVED',followUp:false,password:'Seller123!'});saveApplications(applications)}
seedDemoApplicant();
function showModal(id){document.getElementById(id).style.display='grid'}function hideModal(id){document.getElementById(id).style.display='none'}function showLogin(){showModal('login')}function hideLogin(){hideModal('login')}function hideSupport(){hideModal('support')}function hidePasswordSetup(){hideModal('passwordSetup')}
function requestFollowUp(){const id=localStorage.getItem('vslApplication'),applications=getApplications(),application=applications.find(item=>item.id===id);if(application){application.followUp=true;saveApplications(applications)}showModal('support')}
permitSelect.addEventListener('change',()=>{supportingDocLabel.childNodes[0].nodeValue=permitSelect.value==='yes'?'Business Permit ':'NBI / supporting document '});
document.getElementById('appForm').addEventListener('submit',event=>{event.preventDefault();const application={id:'VSL-2026-'+Math.floor(100000+Math.random()*900000),name:document.getElementById('appName').value.trim(),email:document.getElementById('appEmail').value.trim().toLowerCase(),mobile:document.getElementById('appMobile').value.trim(),address:document.getElementById('appAddress').value.trim(),hasPermit:permitSelect.value,status:'UNDER REVIEW',followUp:false,password:null},applications=getApplications(),viewerAccounts=JSON.parse(localStorage.getItem('vslViewerAccounts')||'[]'),result=document.getElementById('result');if(applications.some(item=>item.email.trim().toLowerCase()===application.email)||viewerAccounts.some(item=>item.email.trim().toLowerCase()===application.email)){result.innerHTML='<span style="color:#c5252b;font-weight:700">This email has already been registered. Please use another email.</span>';return}applications.push(application);saveApplications(applications);localStorage.setItem('vslRegisteredEmails',JSON.stringify([...new Set([...JSON.parse(localStorage.getItem('vslRegisteredEmails')||'[]'),application.email])]));localStorage.setItem('vslApplication',application.id);result.innerHTML='<b>Application submitted!</b><br>Your tracking ID: '+application.id+'<br>Status: UNDER REVIEW<br><button class="primary" type="button" onclick="requestFollowUp()">Contact Support to Follow Up</button>';event.target.reset();supportingDocLabel.childNodes[0].nodeValue='NBI / supporting document '});
function loginApplicant(){const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value,application=getApplications().find(item=>item.email===email),message=document.getElementById('loginMessage');if(!application){message.textContent='No application was found for this email.';return}if(application.status!=='APPROVED'){hideLogin();showModal('support');return}if(!application.password){localStorage.setItem('vslPasswordSetupEmail',application.email);hideLogin();showModal('passwordSetup');return}if(application.password!==password){message.textContent='Incorrect password. Please try again.';return}localStorage.setItem('vslCustomerSession',application.email);location.href='customer-dashboard.html'}
function savePassword(){const password=document.getElementById('newPassword').value,confirmPassword=document.getElementById('confirmPassword').value,message=document.getElementById('passwordMessage'),email=localStorage.getItem('vslPasswordSetupEmail');if(password.length<6){message.textContent='Password must have at least 6 characters.';return}if(password!==confirmPassword){message.textContent='Passwords do not match.';return}const applications=getApplications(),application=applications.find(item=>item.email===email);if(!application){message.textContent='Application not found.';return}application.password=password;saveApplications(applications);localStorage.removeItem('vslPasswordSetupEmail');localStorage.setItem('vslCustomerSession',application.email);location.href='customer-dashboard.html'}
